name: Code Quality Check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: [push]

jobs:
  server_check:
    name: Code style and type checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Code Checks
        run: pnpm checks
